all:
	clear
	./../../../jasminc -o compiled_Jasmin/mpc_AND.s  mpc_AND.jazz
	./../../../jasminc -o compiled_Jasmin/mpc_MAJ.s  mpc_MAJ.jazz
	./../../../jasminc -o compiled_Jasmin/mpc_ADD.s  mpc_ADD.jazz
	./../../../jasminc -o compiled_Jasmin/mpc_ADD_hHa.s  mpc_ADD_hHa.jazz
	./../../../jasminc -o compiled_Jasmin/mpc_ADD_K.s  mpc_ADD_K.jazz
	./../../../jasminc -o compiled_Jasmin/mpc_ADD_W.s  mpc_ADD_W.jazz
	